# Don't print a new line at the start of the prompt
add_newline = false

[aws]
disabled = true

[battery]
disabled = true

[java]
disabled = true

[kubernetes]
disabled = false

[line_break]
disabled = true

[time]
disabled = false
