# Don't print a new line at the start of the prompt
add_newline = false

[aws]
disabled = false

[battery]
disabled = true

[git_commit]
commit_hash_length = 8
only_detached = false
tag_disabled = false
disabled = false

[git_metrics]
disabled = false
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[java]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = false

[line_break]
disabled = false

[ruby]
disabled = false

[status]
disabled = false

[sudo]
disabled = false

[time]
disabled = true
