# Don't print a new line at the start of the prompt
add_newline = false

[aws]
disabled = true

[battery]
disabled = true

[git_commit]
commit_hash_length = 8
only_detached = false
tag_disabled = false
disabled = false

[java]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[line_break]
disabled = true

[status]
disabled = false

[time]
disabled = true
